### ISSUE TITLE
reticulum

### ISSUE THREAD

**Issue by fab1an2** [geoffwhittington/meshtastic-matrix-relay#64]
Is possible add https://reticulum.network/manual/interfaces.html reticulum bridge?
It have simple pipe interface.

**Comment by jeremiah-k** [comment]
> Is possible add https://reticulum.network/manual/interfaces.html reticulum bridge? It have simple pipe interface.

Hi. I'm finally finding some time to work on this project again. At the moment, I'm trying to get the issues straightened out.  I'm only vaguely familiar with Reticulum and how it functions. I don't know if I'd be the one to implement it, but we do have a plugin system and accept contributions.

I am curious, can you describe how you think this bridge should work?
